# Generated by Django 5.0 on 2023-12-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_servicio_user_delete_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDeCobro',
            fields=[
                ('idMetod', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('descripcion', models.TextField(max_length=299)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id',
        ),
        migrations.AddField(
            model_name='servicio',
            name='idServicio',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AddField(
            model_name='categoria',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.servicio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.servicio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idMetodoDeCobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.metododecobro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idMetodoDePago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.metododepago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.producto'),
        ),
    ]
